### ISSUE TITLE
Check for duplicate tables in SubmissionFileValidator

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#24]
The record https://www.hepdata.net/record/ins778396?version=2 caused problems in HEPData/hepdata#305 because the `submission.yaml` file contains duplicate tables:
```yaml
name: "Figure 7, p + p collisions"
description: 'RHS versus $p^b_T$ for p + p collisions for four trigger selections. '
keywords:
  - {name: reactions, values: [P P --> CHARGED X]}
  - {name: cmenergies, values: [200.0]}
  - {name: phrases, values: [ppg083, correlations]}
additional_resources:
  - {location: thumb_rhs1.png, description: Thumbnail Image file}
  - {location: rhs1.png, description: Image file}
data_file: rhs1_pp.yaml
---
name: "Figure 7, Au + Au collisions"
description: 'RHS versus $p^b_T$ for Au + Au collisions for four trigger selections. '
keywords:
  - {name: reactions, values: [AU AU --> CHARGED X]}
  - {name: cmenergies, values: [200.0]}
data_file: rhs1_auau.yaml
---
name: "Figure 7, p + p collisions"
description: 'RHS versus $p^b_T$ for p + p collisions for four trigger selections. '
keywords:
  - {name: reactions, values: [AU AU --> CHARGED X]}
  - {name: cmenergies, values: [200.0]}
data_file: rhs1_pp.yaml
---
name: "Figure 7, Au + Au collisions"
description: 'RHS versus $p^b_T$ for Au + Au collisions for four trigger selections. '
keywords:
  - {name: reactions, values: [AU AU --> CHARGED X]}
  - {name: cmenergies, values: [200.0]}
data_file: rhs1_auau.yaml
```
The `SubmissionFileValidator` should check that the `name` (and maybe also the `data_file`) of each table is unique in the documents of `submission.yaml`.
