### ISSUE TITLE
Only make additional Python checks if no schema errors

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-validator#40]
I've noticed a few recent error emails from the submission system with `An unexpected error occurred: float() argument must be a string or a number, not 'NoneType'` and an exception raised in Sentry ([example](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/29742/?environment=production&referrer=alert_email)) with `Final attempt of process_saved_file for recid 1636571704 failed. Resetting to previous status.`  This happens because null values are given for some fields, e.g.
```yaml
dependent_variables:
- header: {name: '$d^{2}\sigma/d\it{p}_{T}d\eta(mb \it{c}/GeV)$'}
  qualifiers:
  - {name: '$\it{p}_{T,jet}^{ch} (GeV/c)$', value: 'Jetptg R=0.2'}
  values:
  - value: 
    errors:
    - {symerror: , label: '$p_{T}$ statistical'}
    - {symerror: , label: '$p_{T}$ systematic'}
  - value: 
    errors:
    - {symerror: , label: '$p_{T}$ statistical'}
    - {symerror: , label: '$p_{T}$ systematic'}
```
Here, the `value` and `symerror` will show as `None` in Python, giving an uncaught exception `TypeError: float() argument must be a string or a number, not 'NoneType'` from [`error = float(error)`](https://github.com/HEPData/hepdata-validator/blob/9c38835252c4b615b9100a09cf5e32902c80b000/hepdata_validator/data_file_validator.py#L260).  Probably it would be easier just to make the additional Python checks such as `check_for_zero_uncertainty` if there are no validation errors from the JSON schema (i.e. revert a change made in https://github.com/HEPData/hepdata-validator/commit/dd5d463de77898579f1f108d5dbe711f694c5d88).  Otherwise, the Python code making the additional checks cannot make any assumptions about the validity of the fields.

Could you please address this issue, @alisonrclarke, together with #39?
