### ISSUE TITLE
Define GitHub Actions CI

### ISSUE THREAD

**Issue by Sinclert** [HEPData/hepdata-validator#9]
Continuing with issue https://github.com/HEPData/hepdata-validator/issues/8, I would also suggest to create a very basic GitHub Actions CI workflow, given that there are some nice tests already defined.

The `ci.yml` may look something like:
```yaml
name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:

  test:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v2
    - name: "Set up Python 3.6"
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: "Install Python dependencies"
      run: |
        pip install -r requirements.txt
    - name: "Test with pytest"
      run: |
        cd testsuite && pytest
```
